#!/bin/bash -e

case "$1" in
    configure)
    # Install pipd dependencies
    pip3 install -r /usr/share/doc/azure-cert-rotation/requirements.txt
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
